services:
  server:
    build: server
    ports:
      - 5050:5050

    container_name: auth-server
    user: nobody

  client:
    build: client
    container_name: auth-client
    links:
      - server
    user: nobody
